name: Deploy

on:
  workflow_run:
    workflows: [Check]
    branches: [master]
    types: [completed]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Deploy with Heroku
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/calm-lowlands-37292.git HEAD:master -f
